### ISSUE TITLE
installation errors

### ISSUE THREAD

**Issue by samhiddenhand** [ymcatwincities/openy#1316]
I got this error when trying a fresh install with OpenY 8.x-1.14--dev

using English and MySQL

<img width="709" alt="screen shot 2018-09-28 at 12 51 48 pm" src="https://user-images.githubusercontent.com/1124229/46234203-6aa45f00-c32a-11e8-87fe-446816ab272a.png">
<img width="737" alt="screen shot 2018-09-28 at 12 52 14 pm" src="https://user-images.githubusercontent.com/1124229/46234205-6aa45f00-c32a-11e8-921d-d8740f5cd914.png">
<img width="664" alt="screen shot 2018-09-28 at 12 52 20 pm" src="https://user-images.githubusercontent.com/1124229/46234206-6aa45f00-c32a-11e8-86ee-a59a4beed4a2.png">

**Comment by ddrozdik** [comment]
@samhiddenhand try now the latest dev version, should work now.

**Comment by samhiddenhand** [comment]
I just installed again using the command:

`composer create-project ymcatwincities/openy-project:8.1.x-development-dev MY_PROJECT --no-interaction --no-dev`

which is supposed to install the latest dev version... but it gave me OpenY 8.x-1.14-dev, and when I installed it, I got the same exact error. Screenshots attached. Does this command need to be updated?

<img width="709" alt="screen shot 2018-10-03 at 11 46 21 am" src="https://user-images.githubusercontent.com/1124229/46431996-073b7800-c702-11e8-88df-b86a64a8b087.png">
<img width="728" alt="screen shot 2018-10-03 at 11 46 28 am" src="https://user-images.githubusercontent.com/1124229/46431997-073b7800-c702-11e8-9684-3fcf8991e548.png">
<img width="723" alt="screen shot 2018-10-03 at 11 46 34 am" src="https://user-images.githubusercontent.com/1124229/46431998-073b7800-c702-11e8-8151-6ca5d22b7a8f.png">

**Comment by ddrozdik** [comment]
Adding following screenshots from the Open Y Slack for history purposes: 
@samhiddenhand reported that they can't install Open Y on their server and attached screenshots from the Installation interface(see above). Later in the conversation, we identified that the problem was in the process of applying patches via composer, see below:
<img width="1095" alt="screen shot 2018-10-05 at 10 43 00 am" src="https://user-images.githubusercontent.com/6285570/46797500-fe792080-cd57-11e8-801d-730cacbe9e12.png">
<img width="1082" alt="screen shot 2018-10-05 at 10 43 12 am" src="https://user-images.githubusercontent.com/6285570/46797501-fe792080-cd57-11e8-8dab-e144242f0d6e.png">
<img width="1095" alt="screen shot 2018-10-05 at 10 43 27 am" src="https://user-images.githubusercontent.com/6285570/46797503-fe792080-cd57-11e8-98f4-e88f558986ba.png">
<img width="1092" alt="screen shot 2018-10-05 at 10 43 41 am" src="https://user-images.githubusercontent.com/6285570/46797504-ff11b700-cd57-11e8-9f29-f41575a9d0c6.png">

**Comment by ddrozdik** [comment]
@samhiddenhand After getting access to the server I notices a few issues:
1. Installed composer version is a DEV version. - I recommend to use only stable versions. 
2. Composer commands should not be run under root user, but they were. Read more why it's not recommeneded to use root user - https://getcomposer.org/root
3. Patches were not applied due to missing `patch` command on the server.  This command is important for composer and for some reason was not installed when composer was installed.
<img width="719" alt="1 ddrozdik jlkk-7gx8 tmp ssh 2018-10-11 13-22-48" src="https://user-images.githubusercontent.com/6285570/46797780-c6bea880-cd58-11e8-8229-48240b3201bf.png">

So, to fix this issue and install Open Y correctly I recommend:
1. Install `patch` command. 
Since you are using Red Hat for your Linux distribution the command is `yum install patch`.
You can read more about this command here https://access.redhat.com/documentation/en-us/red_hat_jboss_a-mq/6.3/html/console_reference/consolepatch 
2. Downgrade composer version to the latest stable version
2. Install Open Y from scranch using the latest stable version `composer create-project ymcatwincities/openy-project openy --no-interaction --no-dev`

**Comment by YMCA-GTC** [comment]
Thank you for all of your work on this @ddrozdik !
