### ISSUE TITLE
Time not displaying properly for some events when using Carnation theme

### ISSUE THREAD

**Issue by YMCA-GTC** [ymcatwincities/openy#1423]
See this thread on Open Y Slack for details. https://openy.slack.com/archives/C6G4ZTLVC/p1546894459018400

GRYMCA has an event that is scheduled from 10a - 12p, but the display on their site says 3p - 5p. It is 5 hours off. After some brief debugging, @ygerasimov feels this is a simple bug with Carnation that we should fix, with the details in the Slack thread above.

Please also check that this issue is not occurring for the other themes, and if so, please fix it there as well.

Assigning to IXM for resolution.

**Comment by jwtechdesign** [comment]
Here's a temporary fix that worked for me.  The incorrect time for me shows on the Upcoming Events paragraph section, which uses a View to pull the latest events.  It uses the "Teaser" display to pull those events in the view.  So you'll want to do 2 things: 

1) Force the correct timezone on the format display of the Date field, on the "Events" Content Type.  Do that under "Structure > Content types > Event > Manage display > Teaser" (using your own desired settings):

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/32372465/56763380-e2732480-6767-11e9-8377-845d7a78ac75.png">

2) Update the twig template file in the codebase.  The file is located under your theme, "your_theme/templates/node/event/node--event--teaser.html.twig".  You'll want to update the variable pulling the event time, to use the field data instead of the UTC time.  I did that by changing line 112 from:

`<i class="far fa-clock"></i> {{ node.field_event_dates.value|date('g:i a') }}` 
to 
`<i class="far fa-clock"></i> {{ content.field_event_dates }}`

_Note: this will show both start and end times._

**Comment by anpolimus** [comment]
@podarok , this PR is merged.
Can we close this issue?
