### ISSUE TITLE
Inconsistent Breadcrumbs in Carnation

### ISSUE THREAD

**Issue by jwtechdesign** [ymcatwincities/openy#1467]
In the Carnation theme, breadcrumbs on program pages, program subcategory and landing pages will sometimes use "Current page" as the page title (and the last item in the breadcrumb), instead of the actual page's title.  For example, on a landing page called "Military Added Benefits" here is the breadcrumb showing:

<img width="649" alt="image" src="https://user-images.githubusercontent.com/32372465/51406572-29c19780-1b1f-11e9-9e10-db0e887b088a.png">

As opposed to another landing page correctly using the page title as the breadcrumb's final item:

<img width="595" alt="image" src="https://user-images.githubusercontent.com/32372465/51406610-43fb7580-1b1f-11e9-9a8d-09f6378a84c0.png">

It should be noted, that the breadcrumbs show correctly in the Lily & Rose themes.  Carnation seems to be where the discrepancy happens.

Unfortunately, I cannot find a pattern to recreate the issue.  I've seen it pop up on multiple content types (listed above), on pages that were part of the initial install, and on pages that were created fresh after install.  I will continue to research and see if I can narrow down a user story to recreate the bug, but wanted to put it on the radar in case others are experiencing the same issue.

**Comment by YMCA-GTC** [comment]
This one is tricky to reproduce, but has now been reported by two agencies. Assigning to IXM to resolve.

**Comment by aaronjchristian** [comment]
Ah okay, so I can explain why this is happening and what I did to alleviate the issue. 

The short of it all, we are replacing titles in the active breadcrumb which are over 20 characters in length with "Current Page". 

This is to prevent the breadcrumbs from breaking onto 2 lines on tablet devices since this uses a "tabbed" arrow style of design. 

When you start to drill down into the programs/activities the breadcrumbs can become quite lengthy and this was a remedy while in the early stages of developing carnation.

The main thing to note here is that we have two very different breadcrumb designs, lily & rose use similar styles with a "/" divider, with a smaller font size, where carnation uses the tabs with a larger font size.

**Comment by jwtechdesign** [comment]
Got it! Thank you for the response, @aaronjchristian.  This makes sense, and now with your explanation I see that logic in the openy_carnation.theme file. 

It would seem, then, that this is NOT a bug and is actually functioning just as expected.  @YMCA-GTC, looks like we can probably downgrade this, if not close it out.  Thanks again!

**Comment by aaronjchristian** [comment]
No problem @jwtechdesign!

Yes if you wish to override or revert this sort of feature, you can do so in your custom child-theme by writing your own **hook_preprocess_breadcrumb()** function inside **your_theme.theme** file.

Hope that helps!
