### ISSUE TITLE
[Activity Finder] Issues in 2.0 version

### ISSUE THREAD

**Issue by hamrant** [ymcatwincities/openy#1738]
Some issues that our QA have found during testing Activity Finder update from 1.0 to 2.0 version.
I think this should be fixed in 3.0 or in the minor release.

### 1. Age or Days filter

If you applying Age or Days filter - after 1 click filter collapsing. On 1.0 version, filters are not collapsing. From UX perspective user more often selects several values, therefore, this change may be inconvenient for the average user.

![f91ae281-bb23-48a9-bb8a-c368ed5d8341](https://user-images.githubusercontent.com/13733670/65135087-03396080-da0e-11e9-9e43-c76e79d14e04.png)

### 2. Sorting by title are not correctly sorted

![e5f4f9b0-c03c-46a6-ae9c-b9a898f82dbc](https://user-images.githubusercontent.com/13733670/65135232-3d0a6700-da0e-11e9-965a-b353f97f15c7.png)

### CURRENT SCOPE

1. If no result page is shown for some reason, Day filter became grey (like blocked) but can be clicked anyway. Other filters are active. This makes no sense. This feature should be modified.
2. Add Age button at nothing found block and clear all except Age fields at search filters.
3. Activity popup in landscape mode can be scrolled so that mean can not be closed.
4. Sorting by title are not correctly sorted

**Comment by hamrant** [comment]
Can someone from IMX team look at this and fix it?

**Comment by podarok** [comment]
@hamrant it's better to discuss all UX questions with Ben McCoy @paige-kiecker

**Comment by anpolimus** [comment]
@hamrant that was requirement for 2.0 version

**Comment by anpolimus** [comment]
@hamrant also I want you to introduce to ActivityFInder 3.0
http://houston.activity-finder.openy.ixm.ca/program-search?locations=&categories=&exclude=&ages=&days=&keywords=&no_results=0&sort=DESC__score
http://rose.activity-finder-solr.openy.ixm.ca/program-search?locations=&categories=&exclude=&ages=&days=&keywords=&no_results=0&sort=title__ASC

**Comment by hamrant** [comment]
Hi @anpolimus 

Thanks for the links to ActivityFInder 3.0! It looks like the second item from the list fixed in 3.0, but the first one still exists.

**Comment by anpolimus** [comment]
Yes, you are right. I'm not 100% sure, but it seems to me that logic from your first item was a requirement for AF2.0.
I'll double check with Ben today and will answer you here.

**Comment by anpolimus** [comment]
@hamrant  ^^

**Comment by hamrant** [comment]
@anpolimus ok, thanks

**Comment by konservax** [comment]
@paige-kiecker cc
additional bugs for activity finder:
1. in the keywords search field - if user will insert short word up to 4 symbols - no result will be shown.
Better to let users show all result according to word or letter what was inserted in the field.
Or User at least should be notified about this field validation.

2. If no result page is shown for some reason, Day filter became grey (like blocked) but can be clicked anyway.  Other filters are active. This makes no sense. This feature should be modified. 

3. If the user typed short word ( up to 4 symbs ), got no result page, And clicked on buttons:
What criteria is most important to you?  -day, program, Location - no result will be shown. So a new search will be applied with the keywords search filter. 

4. I would improve No result page with New button - What criteria is most important to you? *Age*

![image](https://user-images.githubusercontent.com/49909896/65774241-86616180-e146-11e9-8234-9b8a44a4df27.png)

**Comment by konservax** [comment]
5.  layout issue for search result page (activity-finder)
mobile version. Android 8. Device : Huawei P20pro
![image](https://user-images.githubusercontent.com/49909896/65775147-4bf8c400-e148-11e9-93de-0641a30d2595.png)

6. Activity popup  in landscape mode can be scrolled so that mean can not be closed.  
![image](https://user-images.githubusercontent.com/49909896/65775979-da217a00-e149-11e9-95ac-a73599f94715.png)

7. grey corner should be centered due to bottom of popup
![image](https://user-images.githubusercontent.com/49909896/65776127-1e147f00-e14a-11e9-88cc-94180d134847.png)

**Comment by konservax** [comment]
8. EDGE browser (latest version). missed loupe icon for activity finder page
![image](https://user-images.githubusercontent.com/49909896/65776690-4b156180-e14b-11e9-9f0b-fd2992a384f3.png)

**Comment by anpolimus** [comment]
Hi, @konservax.
I'm trying to review your requests and have some comments.

> in the keywords search field - if user will insert short word up to 4 symbols - no result will be >shown.

I've tried **age** keyword search and can see results.
This issue is connected to the configuration of your Apache Solr index and search engine.
Activity Finder works as an interface for your search backend. You could improve your search index at YMCAGBW and get better results. Activity Finder ships with a basic installation which with a high level of probability overwritten by your team.

> Better to let users show all result according to word or letter what was inserted in the field.
> Or User at least should be notified about this field validation.

Showing all results in case of **nothing found** require's @paige-kiecker approve. I'll discuss it with her.

**Comment by anpolimus** [comment]
> I would improve No result page with New button - What criteria is most important to you? Age
>This improvement is great. I see that day-program buttons are not working at all for now.

We will discuss it and return back to you.

**Comment by anpolimus** [comment]
> layout issue for search result page (activity-finder) mobile version. Android 8. Device : Huawei 

P20pro

@konservax 
_View registration info for our next session._ - this text is added by your team at your project.
This means that this issue should be fixed in the scope of your project. This is not AF issue.
Here is the place where this code is stored:
https://github.com/YMCA-GBW-ORG/ymcabrandywine/blob/4317cb1e5ae1c256a720a6fb95d5102c4427e08a/docroot/themes/custom/ymca_seattle/templates/custom/class-page-other-sessions.html.twig#L51

**Comment by anpolimus** [comment]
> grey corner should be centered due to bottom of popup

@konservax, could you please add some details to this issue?

**Comment by YMCA-GTC** [comment]
Hi @anpolimus We are working on AFv4 for May 2020 and much of these items will be addressed in that release. The bugs above will be resolved, and we will bring in the Age option for the null results experience. Our hope is to have this in the May release. More info will be shared soon by the Five Jars team who are taking this on. No need to duplicate efforts. Thank you!

**Comment by duozersk** [comment]
Hi @anpolimus ! As mentioned above by Craig (I believe it was Craig ;)) we are actively working on the AFv4 - which is in general some enhancements on the backend side and completely re-written frontend code. I've skimmed through the bugs reported here and all of them are not present in this new version.
Let's connect in Slack if you want to have more details about it and we can also setup a call to discuss the upcoming changes, what was improved, how it is going to be integrated into Open Y, etc.
The timeline for AFv4 coming into Open Y should be in May release, in the mean time we are actively working with YGTC team to get it ready to use on their site first.

**Comment by anpolimus** [comment]
@duozersk, I know.
We are communicating now for holding this until v4 release

**Comment by hamrant** [comment]
Looks like the issue can be closed, thanks to all!
