### ISSUE TITLE
Aligned Images Disappear

### ISSUE THREAD

**Issue by jwtechdesign** [ymcatwincities/openy#1878]
**[Carnation Theme]
[openy-8.x-2.3.5]**

-------

Whenever an embedded image is aligned, it appears in the editor, but does not show at all on the saved page.  I've tested this on multiple WYSIWYG enabled editors, and the issue happens in all instances an embedded image is aligned to anything besides "none".

<img width="527" alt="image" src="https://user-images.githubusercontent.com/32372465/73094422-27b6b500-3ea6-11ea-9467-05783b297810.png">

-------

**Steps to Recreate:**

- Log into Sandbox 
- Edit any Page that contains a WYSIWYG editable field.  (http://sandbox.openymca.org/about - for example)
- Edit the "Simple Content" paragraph section under "Content Area" & add an image to the section using the "Image Embed" button in the WYSIWYG editor
- Choose one of "Align Left/Center/Right" & Embed (Image will appear in editor)
- Save the Page (Image does not appear on the Page)

**Comment by paige-kiecker** [comment]
@podarok please investigate

**Comment by podarok** [comment]
@dmytrolavrinenko @shuklina to provide an update on this from YGTC

**Comment by akaleMulder** [comment]
We have encountered the same issue on Carnation on [openy-8.x-2.4.4]. It seems that the only way to get the image displayed is to leave alignment untouched (so align is 'none'). But the problem is that the image is displayed as really large.

On this screenshot the image that I uploaded is just 256x256px.
<img width="1440" alt="Screen Shot 2020-05-07 at 13 14 42" src="https://user-images.githubusercontent.com/2506214/81265522-0c427500-9065-11ea-8683-fc6c96716ca5.png">

**Comment by sarah-halby** [comment]
@akaleMulder was this item addressed with the Carnation refactoring? @jwtechdesign is this still an issue for you or was this addressed for you in the most recent release?

**Comment by jwtechdesign** [comment]
@sarah-halby - I've tested it on the Carnation Sandbox (running 8.2.7) and it looks like this is resolved in the latest release!  Thank you!

![image](https://user-images.githubusercontent.com/32372465/99006690-78b49a00-2508-11eb-885d-1f2fc5fffc03.png)
