### ISSUE TITLE
if there are more then 3 items in a camp menu that as the screen size gets smaller menu items disappear

### ISSUE THREAD

**Issue by Robert201-zz** [ymcatwincities/openy#196]
Given I have camp menu setup on the page
And I have more than 4+ links there
When I see the menu on mobile
Then I see only 3 links displayed.
make this menu a slider so user can scroll to the other items

![camp menu on mobile appear](https://cloud.githubusercontent.com/assets/25036221/23458897/f8ae3b3e-fe75-11e6-836d-851e5ffd9076.png)
![camp menu on mobile no longer appears](https://cloud.githubusercontent.com/assets/25036221/23458912/03168086-fe76-11e6-831a-ee62599606b9.png)

**Comment by alexschedrov** [comment]
- Login to site as admin
- Go to "/camps/camp-colman" and edit camp page
- Add more menu items
- Check tablet/mobile layout

**Comment by tolichka** [comment]
@Sanchiz I propose to avoid slider because user should know that he need to drag element to see rest of menus.

But i propose 2 classic variants

1)http://take.ms/vOA9k - show menu list by default, not in 1 row only. Because if a lot menu elements will be added they will fit in blue zone and will be visible and clickable.

2)http://take.ms/RZKPw - make vertical list. But in such case we need to decide when we should switch from horizontal position to vertical list. Because even on desktop a long list can to not fit in 1 row.

So I'm propose variant 1 and depend on menu elements height of blue block will be dynamic. With a few menu elements it will be only 1 row, and when there will be a lot of menu elements than it will be 2 or 3 rows.

**Comment by alexschedrov** [comment]
@tolichka let's re-use approach from this website(OpenY prototype). In this case with shadow user will understand that he have to slide to get rest of menu items.
http://www.seattleymca.org/camps/orkila

![image](https://cloud.githubusercontent.com/assets/1316234/26725036/25e529d2-47a5-11e7-899e-0e71f235dce5.png)

**Comment by tolichka** [comment]
@Sanchiz I have added js and it works great. But on example page you can see that active state for menus is removed. And on mobile they also dont have hover. They did it to avoid of overlapping gradients and hover states. So my question is do we need also remove active state and hover for mobile screen sizes on menus. As in example?

**Comment by alexschedrov** [comment]
@tolichka let's have active state and hover. Seems they're missed in Seattle's site. Since shadow is for general element, I think it's fine to keep active state and hover for elements itself.
