### ISSUE TITLE
Alerts Improvements

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#2332]
**Preconditions:** 
Open Y 2.7.0 
Theme: Carnation
Type: Fresh custom installation

**Improvements:**
1. The left and right arrow can be hidden when there are no alerts to show, so the user can understand this is the first or last alert in the list 
![image](https://user-images.githubusercontent.com/6285570/101829695-76178580-3b44-11eb-877e-a28f4e50a944.png)

2. Call to action button has no hover and focus styles. This button does not interact with the user, it looks like a static thing. 
![image](https://user-images.githubusercontent.com/6285570/101829767-98a99e80-3b44-11eb-887f-d761bc95dd03.png)

3. On Desktop alerts in the footer has an issue with alignment
![image](https://user-images.githubusercontent.com/6285570/101829819-abbc6e80-3b44-11eb-8015-e85feb3068ef.png)

**Comment by podarok** [comment]
Hi @ddrozdik 
I believe QA is confused with timezone settings
Please, have a look at the smoke test I've created just now https://youtu.be/MH4BwMowlic

In order to have Scheduler working for you
- ensure your site timezone set properly
- ensure your user timezone(if allowed) set properly
- create unpublished Alert with a time in the future
- wait for the time to arrive
- run cron
- verify Alert is published

**Comment by sarah-halby** [comment]
Discussed this as minor UX improvements - we will add to the to-do list and prioritize with the Core Team in 2021.

**Comment by sarah-halby** [comment]
This issue was addressed in this PR: https://github.com/ymcatwincities/openy/pull/2414 Closing ticket.
