### ISSUE TITLE
Scheduler is not working properly

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#2334]
**Environment:**
Environment: https://sandboxes-d9.openy.org/
Open Y Type: Custom
Version: 2.7.1

**Steps to test:**
1. Login as Admin 
2. Go to Content 
3. Create a new Alert 
4. Fill the form 
5. In the Scheduling options specify publish/unpublish on date and time 
6. Go to the page Content -> Scheduled (tab) or /admin/content/scheduled
7. Verify you can see just created alert in the list 
8. Verify alert published on specified date and time 
9. Verify alert unpublished on specified date and time 

_Note: While testing you can specify the current date and time +5 minutes and run cron manually._

**Current Results:**
1. Alert was not published after cron execution completed. 
2. Alert was not unpublished after cron execution completed.

**Expected Results:**
1. Scheduled to be published on a specific date and time page is published.
2. Scheduled to be unpublished on a specific date and time page is unpublished.

**Comment by podarok** [comment]
Hi @ddrozdik 
I believe QA is confused with timezone settings
Please, have a look at the smoke test I've created just now https://youtu.be/MH4BwMowlic

In order to have Scheduler working for you
- ensure your site timezone set properly
- ensure your user timezone(if allowed) set properly
- create unpublished Alert with a time in the future
- wait for the time to arrive
- run cron
- verify Alert is published

**Comment by ddrozdik** [comment]
@podarok thanks, we will check one more time.

**Comment by ddrozdik** [comment]
@podarok I've got a confirmation that the scheduler is working correctly. The issue was related to the timezone setting on the user level. Our steps in the test case were updated accordingly. 

Thank you for your help. 
Closing this issue.

**Comment by podarok** [comment]
Thank YOU @ddrozdik and your team
As a result, we have confirmed Scheduler is working as well as the first video smoke test arrived on the YouTube channel.
