### ISSUE TITLE
Adjust membership individual page

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#355]
This page is not available for anonymous users, but it would be great to have a little bit better view mode.
![image](https://cloud.githubusercontent.com/assets/1316234/25990641/2032c172-3709-11e7-9fc9-2509041496d8.png)

**Comment by ivan-berezhnov** [comment]
@Sanchiz what do you like see on this page?
Maybe you have some example?

**Comment by alexschedrov** [comment]
Just make it cool :)

1. Update layout to be 12 columns instead of full width
2. Display image thumbnail
3. Re-arrange fields, so they will look good

**Comment by ivan-berezhnov** [comment]
@Sanchiz I run reinstall and after I can see here https://monosnap.com/file/MCOVqqo5RmsL7kAjWxpzzRmf7M5uzH
I don't see the page as you attached with description and image.
Could you give a link to the page?

**Comment by Sanchiz** [comment]
@ivan-berezhnov http://sandbox.openymca.org/join

**Comment by ivan-berezhnov** [comment]
PR #369 merged

**Comment by AlexNetman** [comment]
Now it is displayed like this:
![image](https://cloud.githubusercontent.com/assets/4558228/26636715/49ddc3a6-4626-11e7-9c91-f8cd86bcea5c.png)

I suggest to display it same as in view mode.
![image](https://cloud.githubusercontent.com/assets/4558228/26636755/5efdfe72-4626-11e7-9b5c-7c14ceb0c3a2.png)

So that user see how actually card will be displayed.

**Comment by ivan-berezhnov** [comment]
@Sanchiz Change view as suggested by @AlexNetman ?

**Comment by alexschedrov** [comment]
@ivan-berezhnov No, it's fine to stick to current version.
