### ISSUE TITLE
Hide messages during installation process

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#381]
A few messages appear during installation process. They should be visible only on homepage after installation process.
![image](https://cloud.githubusercontent.com/assets/1316234/26303265/c061da6e-3eef-11e7-9d35-49bd68a412a0.png)

**Comment by podarok** [comment]
@Sanchiz I don't think we should move messages to homepage after installation. Way more useful is to show them once appeared
I don't think users, installing OpenY interested in info/debug messaged you mentioned. Only those, developing OpenY interested in receiving them. But receiving them afterwards is confusing if you are in the middle of the process of debugging or discovery. 
If this ticket is about making install process less confusing for non technical people - then collapsed by default would be enough.
Let me know if this makes sense for you and instead of over-engineering and moving messages in queue to the end of installation we should make them collapsed by default. Once agreed, @ymcagtc @YMCA-GTC let's ask Ben to provide some idea how collapsed messages should look like.

**Comment by YMCA-GTC** [comment]
I am closing this - I believe a lot of these messages were added to the homepage already. Further only advanced users doing a self-install will see these messages, thus I consider this lower priority. We can return to this in the future if needed.
