### ISSUE TITLE
Content placeholders

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#386]
Whenever we load images or some content that is not renderend right away, we should display placeholders like Facebook does.
http://cloudcannon.com/deconstructions/2014/11/15/facebook-content-placeholder-deconstruction.html

![image](https://cloud.githubusercontent.com/assets/1316234/26341734/d6c1c5cc-3f9d-11e7-9c45-19c28cd110db.png)

![image](https://cloud.githubusercontent.com/assets/1316234/26341752/ee4c3a1a-3f9d-11e7-84e5-613737be2c1b.png)

**Comment by YMCA-GTC** [comment]
@Sanchiz Is this part of what you are implementing in the next release?

**Comment by podarok** [comment]
This is a frontend/UX issue. 
I guess this is mostly for review/architecture process documentation and agency/company development culture as well as some sort of development standardization we follow.
To get this task finished would you mind us gather some sort of best practices in relation to Drupal/ReactJS/Vue.js/Angular and content placeholders ( critical CSS we implemented recently in YGTC ) which definitely improve our review/development/architecture/discovery flows?
Frankly speaking - this ticket is more about innovations in UX/Frontend. Would be supe awesome to gather guys like @aaronjchristian @atiupa @Sanchiz @podarok @shuklina @AndreyMaximov Ben Mccoy, probably @YMCA-GTC , @ygerasimov and do brainstorm some technologies that are
- not expensive to implement
- fast to implement
- applicable to our needs ( remember, you are comparing OpenY which is 99% content site and 1% application with Facebook, which is 1% content, 99% application ). Here we should find proper places where we need to add template placeholders ( Schedules, Activity Finder, Alerts(already done partially, etc ))
- we should define our AB tests for this. Idea to have some cool thing should be tested before implementing.
As example - on YGTC we implemented Alerts as fully decoupled application, which is mostly independent from Backend, Frontend, PHP. It is JS built on ReactJS framework. But. Once implemented, given the fact there is not any performance degradation to what end customer sees, Google PageSpeed shows overall performance degradation, because of algorithms, they put in place. So we should be careful about some technics for not leaning us wrong way.

I'm cool with putting template placeholders for new features. Also, I'm cool with AB testing these on our current, medium importance features for not adding any degradation to  what we have already as success.
@ymcagtc @YMCA-GTC your opinion on this appreciated.

**Comment by YMCA-GTC** [comment]
Sounds good to me @podarok . Could you lead the effort to gather the folks you listed to have a brainstorm on technologies that can achieve this desired impact?

**Comment by paige-kiecker** [comment]
This has been resolved via Blazy image loader and some other minor enhancements to improve this issue
