### ISSUE TITLE
Add possibility to import redirects.

### ISSUE THREAD

**Issue by Fant0m771** [ymcatwincities/openy#856]
Often customer send to us request to create a hundred redirects from his old site to new one. It will be great if we have possibility import redirect which was provided by customer.
Attached as example piece of code which I used for import redirects.

`use Drupal\redirect\Entity\Redirect;
use Drupal\Core\Url;

$redirects_from = ["about-us/our-financials/annual-report"];
$redirects_to = ["/leadership-strategy"];

foreach ($redirects_from as $key => $from) {
  $path = \Drupal::service('path.alias_manager')->getPathByAlias($redirects_to[$key]);
  if ($path && $redirects_from[$key] != $redirects_to[$key]) {
    try {
      $redirect = Redirect::create();
      $redirect->setSource($redirects_from[$key]);
      $redirect->setRedirect($path);
      $redirect->setLanguage('en');
      $redirect->setStatusCode('301');
      $redirect->save();
    }
    catch (\Exception $exception) {
      // Logs an error
      \Drupal::logger('create_redirect')->error(
        "Can't create redirect from " . $redirects_from[$key] . " to " . $redirects_to[$key] . " might it already present!"
      );
    }
  }
}`

**Comment by fandm** [comment]
Good idea. I also propose to store the pairs `redirect_from: redirect_to` in the `.yml` file as we did on YMCA Long Island project.

**Comment by podarok** [comment]
We've made this for Dallas and, If I recall it right - for YGTC
Related to https://github.com/ymcatwincities/openy/issues/438

**Comment by podarok** [comment]
On YGTC , during migration we managed to add redirects to .htaccess file instead of having the app(OpenY) responding to redirects. This is more for reasonable number of redirects. If there is a list of 1000+ - then yes, makes sense to work on migration.
We(Open Y) have no blockers to add redirects migration, we are using Drupal core migration for demo content, so
 having same Demo Redirects content with 2-5 redirects in place with respective Landing Page with links that will show how they work - would be nice.
@fandm @Fant0m771 do you have anything already created on your end to use it as a starting point not from scratch? Which Y association you were supporting for migration of redirects?
/cc @ymcagtc

**Comment by fandm** [comment]
Hi @podarok,
No, I have not. I was working on YMCALi more than a year ago, so I don't remember even any migration of redirects.

**Comment by paige-kiecker** [comment]
@podarok should this be added to the roadmap?

**Comment by podarok** [comment]
This is so unique per source site that spending time on it makes no sense.
Closing
