### ISSUE TITLE
How to update OpenY drupal distribution from 8.3.2 to 8.4.3

### ISSUE THREAD

**Issue by rahulm231** [ymcatwincities/openy#904]
Hello All,

I want to update openy drupal distribution from 8.3.2 to newer version of drupal core. Please suggest how to do that. please help..... 
Thanks..

**Comment by YMCA-GTC** [comment]
Assigned to @podarok to provide some documentation, or links to documentation. Once documentation has been added we can close this ticket (but leave it in the history as a reference for others)

**Comment by YMCA-GTC** [comment]
@podarok Is this ticket still valid, or can it be closed now?

**Comment by mattshoaf** [comment]
I think it is still relevant, the reason that it's not a clean update is because you can't replace the project composer file if you've added any additional contrib  modules. I was able to update from 8.3.x to 8.4.x, but had to manually update my project's composer file, I just looked at a diff between 8.3 and 8.4 to see what needed to be added and removed. Looking at the 8.5 branch, I'm sure that we're going to run into the same thing.

**Comment by podarok** [comment]
@mattshoaf we've updated recently our documentation https://github.com/ymcatwincities/openy/wiki/OpenY-upgrade-how-to-for-Developers
Feel free to to try and let us know if there are any issues

**Comment by paige-kiecker** [comment]
@mattshoaf let us know if the documentation above doesn't help. Otherwise closing this ticket for now.

**Comment by mattshoaf** [comment]
Thanks, I've been busy with some other work, but I did get some good info from that. If I have any suggestions after going through the process again I'll let you know.
