### ISSUE TITLE
Replace block_content with custom scalable entity for referencing from paragraphs

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#983]
https://www.drupal.org/project/drupal/issues/2940755

**Comment by danylevskyi** [comment]
We need to make sure that referenced entities are deleted after removing hosting entity.

**Comment by podarok** [comment]
@danylevskyi We are going to have this entity reusable, so removing could be super tricky

**Comment by AlexNetman** [comment]
Hi! Nice finding!
But actually this issue should not be `critical` for OpenY profile.
Because it is using Paragraphs more than Blocks.
Also the sql-patch provided in https://www.drupal.org/project/drupal/issues/2940755 can be used without modifications on most OpenY sites. Because Panels is not part of OpenY profile (and will have no conflict with patch).

**Comment by YMCA-GTC** [comment]
@podarok could you please update us on the status of this ticket, or close if it has been resolved? Thank you very much!

**Comment by podarok** [comment]
This was fixed by Drupal core 8.6
No need to reinvent the wheel. We still use block_content as is without performance issues on 3000+ blocks.
